### ISSUE TITLE
Initial synchronization no more work

### ISSUE THREAD

**Issue by c-geek** [YunoHost-Apps/duniter_ynh#55]
When installing Duniter from YunoHost admin panel, here are the logs I get:

```
2017-06-14T15:38:20+02:00 - [31merror[39m: No block was downloaded
at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
at errnoException (dns.js:28:10)
2017-06-14T15:38:12+02:00 - [31merror[39m: Error: getaddrinfo ENOTFOUND 2a01 2a01:61650
2017-06-14T15:38:12+02:00 - [31merror[39m: Inner hash of block#26250 from %s does not match
2017-06-14T15:38:11+02:00 - [31merror[39m: Inner hash of block#26250 from %s does not match
2017-06-14T15:38:08+02:00 - [36mdebug[39m: Upgrade database...
2017-06-14T15:38:08+02:00 - [36mdebug[39m: Opening SQLite database "/root/.config/duniter/duniter_default/duniter.db"...
2017-06-14T15:38:08+02:00 - [36mdebug[39m: Configuration saved.
2017-06-14T15:38:08+02:00 - [36mdebug[39m: Loading conf...
2017-06-14T15:38:08+02:00 - [36mdebug[39m: Plugging file system...
+ sudo duniter sync duniter.org 10901 --nointeractive
Synchronizing with duniter.org:10901. It may take a while.
+ echo 'Synchronizing with duniter.org:10901. It may take a while.'
```

This is super-weird. Why this "Inner hash" problem? I'm starting on a clean installation (no data, no config, no duniter).

I suggest to remove initial sync, because Duniter already proposes a synchronization on startup. This way we can let the user choose whether he prefers to sync with Ğ1Test or Ğ1.

**Comment by c-geek** [comment]
Also the installation process would be quicker and less subject to errors.

We can let the synchronization errors to the application's execution.

**Comment by c-geek** [comment]
I've tried this new installation process with https://github.com/c-geek/duniter_ynh. The synchronization works perfectly once Duniter has been launched and is out of installation process.

**Comment by M5oul** [comment]
I encounter same issue. That is strange.
Let's go for this solution.
